AWSTemplateFormatVersion: 2010-09-09
Resources:
  VPCInstance:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: vpc-0
  # Create a subnet
  # Add network interface